### ISSUE TITLE
🐞 Bug : 맵 001에 Tilemap_Collision이 일부 잘못 설정됨

### ISSUE THREAD

**Issue by meongmeongmin** [Team-MMMin/Turn-basedRPG#20]
### 설명
- **문제 설명**: 맵 001에 Tilemap_Collision이 일부 잘못 설정되어 있어 올바르게 작동하지 않는다. 이로 인해 캐릭터가 벽을 통과하거나 충돌이 발생하지 않는 등의 문제가 발생한다.

### 재현 단계
1. Unity 프로젝트를 연다.
2. 001 프리팹을 연다.
3. Tilemap_Collision 설정을 확인한다.
4. 잘못된 충돌 설정으로 인해 발생하는 문제를 확인한다.

### 예상 결과
- Tilemap_Collision이 올바르게 설정되어 캐릭터가 벽과 충돌하거나 통과하지 않도록 해야 한다.

### 실제 결과
- Tilemap_Collision이 일부 잘못 설정되어 캐릭터가 벽을 통과하거나 충돌이 발생하지 않는다.

### 스크린샷
- **잘못 설정된 Tilemap_Collision 스크린샷**:
![Image](https://github.com/user-attachments/assets/58302a74-f6de-47b7-a148-6583a1fadba0)
![Image](https://github.com/user-attachments/assets/f0e05e83-369f-4684-adad-c8e2a8ca82ee)

### 해결 방법
- 맵 001의 Tilemap_Collision 설정을 올바르게 수정하여 충돌이 정상적으로 발생하도록 한다.

### 체크리스트
- [x] Tilemap_Collision 설정을 올바르게 수정했는가?
- [x] 캐릭터가 벽과 올바르게 충돌하는가?
- [x] 충돌 설정이 모든 경계와 오브젝트에 올바르게 적용되었는가?

### 추가 참고사항
- Tilemap_Collision 설정이 잘못된 경우, 게임 플레이에 심각한 영향을 미칠 수 있으므로 주의 깊게 확인해야 합니다.
- 다른  Tilemap_Collision 부분도 문제가 없는지 확인해주세요.

### 담당자
- 담당자: @Leeseunggyu3

**Comment by Leeseunggyu3** [comment]
- Failed to load prefab: 001
  UnityEngine.Debug:LogError (object)
  ResourceManager:Instantiate (string, UnityEngine.Transform, bool) (at Assets/@Scripts/Managers/Core/ResourceManager.cs:33)
  MapManager:LoadMap (string) (at Assets/@Scripts/Managers/Contents/MapManager.cs:31)
  GameScene:Init () (at Assets/@Scripts/Scenes/GameScene.cs:16)
  InitBase:Awake () (at Assets/@Scripts/Utils/InitBase.cs:11)

**Comment by meongmeongmin** [comment]
@Leeseunggyu3 001 프리팹과 콜리션 파일을 어드레서블에 추가해보세요.
