### ISSUE TITLE
🐛 Bug: GetOrAddComponent 사용 시 발생하는 MissingComponentException 해결

### ISSUE THREAD

**Issue by meongmeongmin** [Team-MMMin/Turn-basedRPG#8]
### 설명
- **문제 설명**: GetOrAddComponent 메서드를 사용할 때 MissingComponentException이 발생하는 문제가 있다. 이를 해결하기 위해 Extension 스크립트와 Util 스크립트에 GetOrAddComponent 확장 메서드를 추가하여 문제를 해결했다.

### 재현 단계
1. `GetOrAddComponent` 메서드를 사용하여 컴포넌트를 추가하거나 가져온다.
2. 특정 상황에서 `MissingComponentException`이 발생한다.

### 기대 결과
- `GetOrAddComponent` 메서드를 사용할 때 `MissingComponentException`이 발생하지 않아야 한다.
- 필요한 컴포넌트를 추가하거나 기존 컴포넌트를 정상적으로 반환한다.

### 실제 결과
- `GetOrAddComponent` 메서드를 사용할 때 `MissingComponentException`이 발생한다.

### 수정 내역
- Extension 스크립트에 GetOrAddComponent 확장 메서드 추가
  - GameObject에 필요한 컴포넌트를 추가하거나 기존 컴포넌트를 반환하는 기능 구현
- Util 스크립트에 GetOrAddComponent 함수 추가
  - 컴포넌트를 가져오거나 없으면 새로 추가하는 로직 구현
- MissingComponentException 문제 해결을 위해 기존 GetOrAddComponent 호출을 Util.GetOrAddComponent로 변경

### 코드 예시
```cs
// Extension.cs
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public static class Extension
{
    public static T GetOrAddComponent<T>(this GameObject go) where T : UnityEngine.Component
    {
        return Util.GetOrAddComponent<T>(go);
    }
}

// Util.cs
public static class Util
{
    public static T GetOrAddComponent<T>(GameObject go) where T : UnityEngine.Component
    {
        T component = go.GetComponent<T>();
        if (component == null)
            component = go.AddComponent<T>();

        return component;
    }
}

**Comment by meongmeongmin** [comment]
https://forum.unity.com/threads/getoraddcomponent-return-null-unity-2022-3-6f1.1493102/

**Comment by Leeseunggyu3** [comment]
확인
